spring:
  application:
    name: service-registry

    #Nested

    #hello:
    # - one
    # - two
    # - three

server:
  port: 8761

eureka:
  client:
    # prevent fetching its own server list (client list)
    fetch-registry: false
    # server should not register itself as a service
    register-with-eureka: false


  instance:
    ip-address: true